---

- name: nginx site | git clone
  git:
    repo: "{{ site_repo }}"
    dest: "{{ site_dir }}"

- name: nginx site | site config
  copy:
    src: "{{ site_config }}"
    dest: "/etc/nginx/sites-available/{{ site_name }}"
  notify: reload nginx

- name: nginx site | enable site
  file:
    src: "/etc/nginx/sites-available/{{ site_name }}"
    dest: "/etc/nginx/sites-enabled/{{ site_name }}"
    state: link
  notify: reload nginx

- name: nginx site | open ports
  tags:
    - iptables
  iptables:
    ip_version: "{{ item[0] }}"
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item[1] }}"
    jump: ACCEPT
  with_nested:
    - [ ipv4, ipv6 ]
    - "{{ site_ports }}"
  when: "{{ site.ports }}"
  notify: iptables
