---

- name: nginx site | git clone
  git:
    repo: "{{ site_repo }}"
    dest: "{{ site_dir }}"
    depth: 1
    force: yes
    accept_hostkey: yes

- name: nginx site | nginx config
  vars:
    site: "{{ site_name }}"
  include_role:
    name: nginx
    tasks_from: site.yml

- name: nginx site | open ports
  tags:
    - iptables
  iptables:
    ip_version: "{{ item[0] }}"
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item[1] }}"
    jump: ACCEPT
  loop: "{{ q('nested', [ 'ipv4', 'ipv6' ], site_ports) }}"
  notify: iptables
